[package]
name = "big_bucks"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.2", features = ["rayon", "serde", "blas"] }
ndarray-linalg = { version = "0.18.1", features = ["openblas-static"] }
plotters = "0.3.7"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
statrs = "0.18.0"
tokio = { version = "1.52.3", features = ["full"] }

[lib]
name = "big_bucks"
path = "src/lib.rs"

[[bin]]
name = "explore"
path = "src/explore.rs"

[dev-dependencies]
ndarray-rand = "0.16.0"
